project:
  type: website
  output-dir: _site

website:
  title: "Sahil Imtiyaz"
  site-url: "https://jusahil.github.io"
  repo-url: "https://github.com/jusahil/jusahil.github.io"
  navbar:
    title: "Sahil Imtiyaz"
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects and Funding
      - href: talks.qmd
        text: Talks
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    smooth-scroll: true
    link-external-newwindow: true
    page-layout: full

execute:
  freeze: auto
